const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../app/src/main/assets/core.js');
const h=(symbol,currency,quantity,cost)=>({symbol,name:symbol,currency,quantity,cost,account:'ISA',id:symbol});
test('fractional holdings, valuation, positive profit and return',()=>{assert.deepEqual(C.holding(h('AAPL','USD',2.5,100),{price:120,currency:'USD'}),{cost:250,value:300,profit:50,rate:20,currency:'USD',today:null,todayBase:null,todayRate:null})});
test('loss uses blue triangle format, percent rounds to one decimal',()=>{assert.equal(C.signed(-12.345,1,'%'),'▼12.3%');assert.equal(C.signed(12.345,1,'%'),'+12.3%');assert.equal(C.signed(-0.001,1,'%'),'0.0%')});
test('mixed account uses current FX for both cost and valuation',()=>{const s=C.summary([h('005930.KS','KRW',2,70000),h('AAPL','USD',3,100)],{'005930.KS':{price:80000,currency:'KRW'},AAPL:{price:120,currency:'USD'}},1300);assert.equal(s.currencies.KRW.profit,20000);assert.equal(s.currencies.USD.profit,60);assert.equal(s.combined.value,628000);assert.equal(s.combined.cost,530000);assert.equal(s.combined.profit,98000)});
test('missing or mismatched quote is never silently valued as zero',()=>{const s=C.summary([h('AAPL','USD',3,100)],{AAPL:{price:100,currency:'KRW'}},1300);assert.equal(s.missing.length,1);assert.equal(s.combined,null);assert.equal(C.holding(h('AAPL','USD',1,100),{price:NaN,currency:'USD'}),null)});
test('loss rate is weighted by investment cost, not average percentage',()=>{const s=C.summary([h('A','USD',1,100),h('B','USD',1,900)],{A:{price:200,currency:'USD'},B:{price:450,currency:'USD'}});assert.equal(s.currencies.USD.profit,-350);assert.equal(s.currencies.USD.rate,-35);assert.equal(s.combined,null)});
test('numeric inputs support commas and reject zero, negative or infinite',()=>{assert.equal(C.amount('70,000'),70000);for(const x of ['','0','-5','NaN','Infinity'])assert.equal(C.amount(x),null)});
test('restore validation has no watch limit, enforces stable identifiers and account references',()=>{const state={version:1,watch:[],accounts:['ISA'],holdings:[h('AAPL','USD',2.5,100)],rules:[]};assert.equal(C.validateState(state),state);assert.throws(()=>C.validateState({...state,holdings:[{...state.holdings[0],account:'missing'}]}));const many=Array.from({length:60},(_,i)=>({name:'N'+i,symbol:'S'+i,currency:'KRW'}));assert.equal(C.validateState({...state,watch:many}).watch.length,60);assert.throws(()=>C.validateState({...state,watch:[many[0],many[0]]}));assert.throws(()=>C.validateState({...state,holdings:[...state.holdings,...state.holdings]}))});

test('symbol aggregation combines accounts with weighted cost and retains editable lots',()=>{const rows=[{...h('A','KRW',2,100),account:'ISA',id:'a1'},{...h('A','KRW',3,200),account:'연금',id:'a2'},h('B','USD',1.5,80)];const before=JSON.stringify(rows),groups=C.aggregateHoldings(rows);assert.equal(groups.length,2);assert.equal(groups[0].quantity,5);assert.equal(groups[0].purchase,800);assert.equal(groups[0].cost,160);assert.equal(groups[0].members.length,2);assert.equal(C.holding(groups[0],{price:180,currency:'KRW'}).profit,100);assert.equal(JSON.stringify(rows),before);assert.equal(groups[1].quantity,1.5)});

test("today's P/L uses previous close, per holding and per summary",()=>{const p=C.holding(h('A','KRW',10,100),{price:120,previous:110,currency:'KRW'});assert.equal(p.today,100);assert.equal(p.todayBase,1100);assert.ok(Math.abs(p.todayRate-100/1100*100)<1e-9);const s=C.summary([h('A','KRW',10,100),h('B','USD',2,50),h('C','KRW',1,10)],{A:{price:120,previous:110,currency:'KRW'},B:{price:60,previous:55,currency:'USD'},C:{price:12,currency:'KRW'}},1000);assert.equal(s.currencies.KRW.today,100);assert.equal(s.currencies.USD.today,10);assert.equal(s.combined.today,100+10*1000);assert.deepEqual(s.noPrevious,['C']);assert.equal(C.holding(h('A','KRW',1,1),{price:5,currency:'KRW'}).today,null)});
test('moveItem reorders without mutating and ignores invalid moves',()=>{const a=['a','b','c','d'];assert.deepEqual(C.moveItem(a,0,2),['b','c','a','d']);assert.deepEqual(C.moveItem(a,3,0),['d','a','b','c']);assert.deepEqual(C.moveItem(a,1,1),a);assert.deepEqual(C.moveItem(a,-1,2),a);assert.deepEqual(C.moveItem(a,1,9),a);assert.deepEqual(a,['a','b','c','d'])});
