const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../app/src/main/assets/core.js');
const h=(symbol,currency,quantity,cost)=>({symbol,name:symbol,currency,quantity,cost,account:'ISA',id:symbol});
test('fractional holdings, valuation, positive profit and return',()=>{assert.deepEqual(C.holding(h('AAPL','USD',2.5,100),{price:120,currency:'USD'}),{cost:250,value:300,profit:50,rate:20,currency:'USD'})});
test('loss uses blue triangle format, percent rounds to one decimal',()=>{assert.equal(C.signed(-12.345,1,'%'),'▼12.3%');assert.equal(C.signed(12.345,1,'%'),'+12.3%');assert.equal(C.signed(-0.001,1,'%'),'0.0%')});
test('mixed account uses current FX for both cost and valuation',()=>{const s=C.summary([h('005930.KS','KRW',2,70000),h('AAPL','USD',3,100)],{'005930.KS':{price:80000,currency:'KRW'},AAPL:{price:120,currency:'USD'}},1300);assert.equal(s.currencies.KRW.profit,20000);assert.equal(s.currencies.USD.profit,60);assert.equal(s.combined.value,628000);assert.equal(s.combined.cost,530000);assert.equal(s.combined.profit,98000)});
test('missing or mismatched quote is never silently valued as zero',()=>{const s=C.summary([h('AAPL','USD',3,100)],{AAPL:{price:100,currency:'KRW'}},1300);assert.equal(s.missing.length,1);assert.equal(s.combined,null);assert.equal(C.holding(h('AAPL','USD',1,100),{price:NaN,currency:'USD'}),null)});
test('loss rate is weighted by investment cost, not average percentage',()=>{const s=C.summary([h('A','USD',1,100),h('B','USD',1,900)],{A:{price:200,currency:'USD'},B:{price:450,currency:'USD'}});assert.equal(s.currencies.USD.profit,-350);assert.equal(s.currencies.USD.rate,-35);assert.equal(s.combined,null)});
test('numeric inputs support commas and reject zero, negative or infinite',()=>{assert.equal(C.amount('70,000'),70000);for(const x of ['','0','-5','NaN','Infinity'])assert.equal(C.amount(x),null)});
test('restore validation enforces watch limit, stable identifiers and account references',()=>{const state={version:1,watch:[],accounts:['ISA'],holdings:[h('AAPL','USD',2.5,100)],rules:[]};assert.equal(C.validateState(state),state);assert.throws(()=>C.validateState({...state,holdings:[{...state.holdings[0],account:'missing'}]}));assert.throws(()=>C.validateState({...state,watch:Array(11).fill({name:'AAPL',symbol:'AAPL',currency:'USD'})}));assert.throws(()=>C.validateState({...state,holdings:[...state.holdings,...state.holdings]}))});

test('symbol aggregation combines accounts with weighted cost and retains editable lots',()=>{const rows=[{...h('A','KRW',2,100),account:'ISA',id:'a1'},{...h('A','KRW',3,200),account:'연금',id:'a2'},h('B','USD',1.5,80)];const before=JSON.stringify(rows),groups=C.aggregateHoldings(rows);assert.equal(groups.length,2);assert.equal(groups[0].quantity,5);assert.equal(groups[0].purchase,800);assert.equal(groups[0].cost,160);assert.equal(groups[0].members.length,2);assert.equal(C.holding(groups[0],{price:180,currency:'KRW'}).profit,100);assert.equal(JSON.stringify(rows),before);assert.equal(groups[1].quantity,1.5)});
