// Fixture prices live only in tests; no demo data is shipped with the Android app.
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../app/src/main/assets');
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!/^[a-z0-9.\-]+$/i.test(name)){res.writeHead(404).end();return}const f=path.join(root,name);if(!fs.existsSync(f)){res.writeHead(404).end();return}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(f))});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});await page.clock.install();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{
    window.__saved='';window.__export='';window.__newsCalls=0;window.Native={state:()=> '{}',cachedQuotes:()=> '{}',save:s=>window.__saved=s,notificationsEnabled:()=>false,monitoring:()=>false,permission:()=>{},monitor:()=>{},open:()=>{},export:s=>window.__export=s,importFile:()=>{},request:(id,action,payload)=>setTimeout(()=>{const p=JSON.parse(payload);let data;
        if(action==='quote'){const prices={'^KS11':2800.12,'^KQ11':850.45,'005930.KS':80000,'069500.KS':38000,AAPL:120,'KRW=X':1300};data={symbol:p.symbol,price:prices[p.symbol]||100,previous:(prices[p.symbol]||100)*.99,currency:p.symbol==='AAPL'?'USD':'KRW',time:Math.floor(Date.now()/1000),fetchedAt:Date.now(),source:'테스트 fixture'};}
        if(action==='search'&&p.query==='200')data=[{symbol:'102110.KS',name:'TIGER 200',currency:'KRW',type:'ETF'},{symbol:'069500.KS',name:'KODEX 200',currency:'KRW',type:'ETF'}];else if(action==='search'&&/^\d{6}$/.test(p.query))data=[{symbol:p.query+'.KS',name:'검색 종목 '+p.query,currency:'KRW',type:'EQUITY'}];else if(action==='search')data=[{symbol:'AAPL',name:'애플 · Apple',currency:'USD',type:'EQUITY'}];
        if(action==='news'){window.__newsCalls++;data=Array.from({length:10},(_,i)=>({title:'[검증용 가상 뉴스] 한국 증시와 ETF 동향 '+(i+1),source:'테스트',link:'https://example.com/',pubDate:new Date().toUTCString()}));}
        if(action==='history')data={points:Array.from({length:250},(_,i)=>({t:Math.floor(Date.now()/1000)-86400*(250-i),p:70000+i*40+4000*Math.sin(i/20)})),high:84000,low:65000,source:'테스트 fixture'};
        window.receive(id,{data});
    },20)};
});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.body.textContent.includes('2,800.12'));assert.equal(await page.locator('.index-quote').count(),2);assert.equal(await page.locator('.watch-card').count(),2);await page.waitForSelector('.watch-card .spark');await page.locator('[data-tab="news"]').click();await page.waitForSelector('.news-item');assert.equal(await page.locator('.news-item').count(),10);await page.locator('[data-tab="watch"]').click();assert.equal(await page.locator('.news-item').count(),0);
assert.equal(await page.locator('header').count(),0);assert.match(await page.locator('.index-time').first().innerText(),/기준.*지연 가능/);assert((await page.locator('.index-panel').boundingBox()).height<85);
await page.locator('#add-watch').click();await page.locator('#query').fill('200');await page.locator('#search-form button').click();await page.waitForFunction(()=>document.querySelector('#search-status').textContent==='검색 결과');assert.match(await page.locator('#search-results').innerText(),/TIGER 200/);await page.locator('#etf-only').click();assert.equal(await page.locator('#etf-only').getAttribute('aria-pressed'),'true');await page.locator('#close-dialog').click();
await page.locator('#add-watch').click();await page.locator('#query').fill('KODEX200');await page.locator('#search-form button').click();await page.locator('.search-result').filter({hasText:'KODEX 200'}).waitFor();await page.locator('#close-dialog').click();
await page.locator('[data-detail="005930.KS"]').first().click();await page.waitForSelector('#chart');assert.match(await page.locator('#history-content').innerText(),/기간 최고가/);await page.locator('#close-dialog').click();
await page.locator('[data-tab="portfolio"]').click();await page.locator('#add-holding').click();await page.locator('.search-result').filter({hasText:'애플'}).click();await page.locator('#new-account').fill('ISA');await page.locator('#quantity').fill('2');await page.locator('#cost').fill('100');await page.locator('#holding-form button[type="submit"]').click();await page.waitForFunction(()=>document.body.textContent.includes('+40.00달러'));assert.match(await page.locator('.hold-metrics .up').first().innerText(),/\+40.00/);
await page.locator('#add-holding').click();await page.locator('.search-result').filter({hasText:'삼성전자'}).click();await page.locator('#quantity').fill('2');await page.locator('#cost').fill('70000');await page.locator('#holding-form button[type="submit"]').click();await page.waitForFunction(()=>document.body.textContent.includes('472,000원'));assert.match(await page.locator('.hero').innerText(),/\+18.0%/);
// All saved accounts must appear even when another account is preselected.
for(const name of ['퇴직연금','일반계좌']){await page.locator('#add-account').click();await page.locator('#account-name').fill(name);await page.locator('#account-form button[type="submit"]').click()}
await page.locator('#add-holding').click();await page.locator('.search-result').filter({hasText:'KODEX 200'}).click();assert.deepEqual(await page.locator('#account option').allTextContents(),['ISA','퇴직연금','일반계좌','+ 새 계좌']);await page.locator('#account').selectOption('퇴직연금');await page.locator('#quantity').fill('1');await page.locator('#cost').fill('40000');await page.locator('#holding-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).holdings.at(-1).account),'퇴직연금');
await page.locator('[data-edit]').last().click();assert.equal(await page.locator('#account').inputValue(),'퇴직연금');await page.locator('#account').selectOption('일반계좌');await page.locator('#holding-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).holdings.at(-1).account),'일반계좌');
for(const width of [320,390,760]){await page.setViewportSize({width,height:844});const boxes=await page.locator('nav button').evaluateAll(bs=>bs.map(b=>({icon:b.querySelector('svg').getBoundingClientRect().bottom,label:b.querySelector('.nav-label').getBoundingClientRect().top})));assert(boxes.every(b=>b.icon+4<=b.label),'Navigation icon and label overlap')}
await page.setViewportSize({width:390,height:844});
fs.mkdirSync(path.resolve(__dirname,'../verification'),{recursive:true});await page.screenshot({path:path.resolve(__dirname,'../verification/portfolio-phone.png'),fullPage:true});
await page.locator('[data-tab="watch"]').click();const cards=await page.locator('.watch-card').evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().top));assert.equal(cards[0],cards[1]);await page.locator('[data-alert="005930.KS"]').click();await page.locator('#target').fill('90000');await page.locator('#alert-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).rules[0].target),90000);
for(const code of ['000660','035420','035720','005380','360750','133690','041510','003550']){await page.locator('#add-watch').click();await page.locator('#query').fill(code);await page.locator('#search-form button').click();await page.locator('.search-result').filter({hasText:code+'.KS'}).click()}
assert.equal(await page.locator('.watch-card').count(),10);await page.locator('#add-watch').click();assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.evaluate(()=>JSON.parse(__saved).watch.length),10);await page.locator('[data-remove-watch="003550.KS"]').click();await page.locator('#yes').click();assert.equal(await page.locator('.watch-card').count(),9);assert.equal(await page.locator('.index-quote').count(),2);await page.waitForFunction(()=>document.querySelectorAll('.watch-card .spark').length===9);
// Reordering persists, with both buttons and a pointer drag handle.
await page.locator('#edit-watch').click();await page.locator('[data-move="0"][data-step="1"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).watch[0].symbol),'069500.KS');
const handle=await page.locator('[data-drag="069500.KS"]').boundingBox(),destination=await page.locator('[data-watch-symbol="005930.KS"]').boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(destination.x+destination.width/2,destination.y+destination.height/2,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>JSON.parse(__saved).watch[0].symbol),'005930.KS');await page.locator('#edit-watch').click();
const visibleCards=await page.locator('.watch-card').evaluateAll(xs=>xs.filter(x=>x.getBoundingClientRect().bottom<innerHeight-76).length);assert(visibleCards>=6,'At least six full cards should fit at 390x844');
await page.locator('[data-tab="news"]').click();const newsCalls=await page.evaluate(()=>__newsCalls);await page.clock.fastForward(300000);await page.clock.runFor(100);assert((await page.evaluate(()=>__newsCalls))>newsCalls,'News must refresh after five minutes');assert.equal(await page.locator('.news-item').count(),10);await page.locator('[data-tab="watch"]').click();
await page.screenshot({path:path.resolve(__dirname,'../verification/watch-phone.png'),fullPage:true});await page.setViewportSize({width:760,height:1000});await page.screenshot({path:path.resolve(__dirname,'../verification/watch-fold.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.locator('[data-tab="settings"]').click();assert.match(await page.locator('#main').innerText(),/엑셀 백업/);assert.doesNotMatch(await page.locator('#main').innerText(),/설정한 목표가/);await page.locator('#export').click();assert.equal(await page.evaluate(()=>JSON.parse(__export).holdings.length),3);const before=await page.evaluate(()=>__saved);await page.evaluate(()=>window.importBackup('{"version":1}'));assert.equal(await page.evaluate(()=>__saved),before);assert.deepEqual(errors,[]);console.log('UI checks passed: chart, KR/US search selection, holdings, mixed account totals, target, backup, phone/fold widths.');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
