// Fixture prices live only in tests; no demo data is shipped with the Android app.
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../app/src/main/assets');
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!/^[a-z0-9.\-]+$/i.test(name)){res.writeHead(404).end();return}const f=path.join(root,name);if(!fs.existsSync(f)){res.writeHead(404).end();return}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(f))});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;try{browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}:{})});const page=await browser.newPage({viewport:{width:390,height:844}});await page.clock.install();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{
    window.__saved='';window.__export='';window.__newsCalls=0;window.__quoteCalls=0;window.Native={state:()=> '{}',cachedQuotes:()=> '{}',save:s=>window.__saved=s,notificationsEnabled:()=>false,monitoring:()=>false,permission:()=>{},monitor:()=>{},open:()=>{},export:s=>window.__export=s,importFile:()=>{},request:(id,action,payload)=>setTimeout(()=>{const p=JSON.parse(payload);let data;
        if(action==='quote'){window.__quoteCalls++;const prices={'^KS11':2800.12,'^KQ11':850.45,'005930.KS':80000,'069500.KS':38000,AAPL:120,'KRW=X':1300};data={symbol:p.symbol,price:prices[p.symbol]||100,previous:(prices[p.symbol]||100)*.99,currency:p.symbol==='AAPL'?'USD':'KRW',time:Math.floor(Date.now()/1000),fetchedAt:Date.now(),source:'테스트 fixture'};}
        if(action==='search'&&p.query==='200')data=[{symbol:'102110.KS',name:'TIGER 200',currency:'KRW',type:'ETF'},{symbol:'069500.KS',name:'KODEX 200',currency:'KRW',type:'ETF'}];else if(action==='search'&&/^\d{6}$/.test(p.query))data=[{symbol:p.query+'.KS',name:'검색 종목 '+p.query,currency:'KRW',type:'EQUITY'}];else if(action==='search')data=[{symbol:'AAPL',name:'애플 · Apple',currency:'USD',type:'EQUITY'}];
        if(action==='news'){window.__newsCalls++;data=Array.from({length:10},(_,i)=>({title:'[검증용 가상 뉴스] 한국 증시와 ETF 동향 '+(i+1),source:'테스트',link:'https://example.com/',pubDate:new Date().toUTCString()}));}
        if(action==='history')data={points:Array.from({length:250},(_,i)=>({t:Math.floor(Date.now()/1000)-86400*(250-i),p:70000+i*40+4000*Math.sin(i/20)})),high:84000,low:65000,source:'테스트 fixture'};
        window.receive(id,{data});
    },20)};
});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.body.textContent.includes('2,800.12'));assert.equal(await page.locator('.index-quote').count(),2);assert.equal(await page.locator('.watch-card').count(),2);await page.waitForSelector('.watch-card .spark');await page.locator('[data-tab="news"]').click();await page.waitForSelector('.news-item');assert.equal(await page.locator('.news-item').count(),10);await page.locator('[data-tab="watch"]').click();assert.equal(await page.locator('.news-item').count(),0);
assert.equal(await page.locator('header').count(),0);assert.match(await page.locator('.index-time').first().innerText(),/기준.*(최근 시세|장중|장마감)/);assert((await page.locator('.index-panel').boundingBox()).height<95);assert.equal(await page.locator('#edit-watch').count(),0);assert.equal(await page.locator('.refresh-icon').count(),1);
await page.locator('#add-watch').click();await page.locator('#query').fill('200');await page.locator('#search-form button').click();await page.waitForFunction(()=>document.querySelector('#search-status').textContent==='검색 결과');assert.match(await page.locator('#search-results').innerText(),/TIGER 200/);assert.equal(await page.locator('#etf-only').count(),0);await page.locator('#close-dialog').click();
await page.locator('#add-watch').click();await page.locator('#query').fill('KODEX200');await page.locator('#search-form button').click();await page.locator('.search-result').filter({hasText:'KODEX 200'}).waitFor();await page.locator('#close-dialog').click();
await page.locator('[data-detail="005930.KS"]').first().click();await page.waitForSelector('#chart');assert.match(await page.locator('#history-content').innerText(),/기간 최고가/);await page.locator('#close-dialog').click();
await page.locator('[data-tab="portfolio"]').click();await page.locator('#add-holding').click();assert.match(await page.locator('#search-status').innerText(),/내 관심종목/);assert.equal(await page.locator('.search-result').count(),2);await page.locator('#market-all,[data-market="ALL"]').click();await page.locator('[data-market="US"]').click();assert.match(await page.locator('#search-status').innerText(),/자주 찾는 종목/);await page.locator('.search-result').filter({hasText:'애플'}).click();await page.locator('#new-account').fill('ISA');await page.locator('#quantity').fill('2');await page.locator('#cost').fill('100');await page.locator('#holding-form button[type="submit"]').click();await page.waitForFunction(()=>document.body.textContent.includes('+40.00달러'));assert.match(await page.locator('.holding-profit.up').first().innerText(),/\+40.00/);
await page.locator('#add-holding').click();await page.locator('.search-result').filter({hasText:'삼성전자'}).click();await page.locator('#quantity').fill('2');await page.locator('#cost').fill('70000');await page.locator('#holding-form button[type="submit"]').click();await page.waitForFunction(()=>document.body.textContent.includes('472,000원'));assert.match(await page.locator('.portfolio-summary').innerText(),/\+18.0%/);assert.match(await page.locator('.portfolio-summary').innerText(),/오늘의 손익/);assert.match(await page.locator('.portfolio-summary .summary-cell.today b').first().innerText(),/^\+/);assert.equal(await page.locator('.holding-today').count(),2);assert.match(await page.locator('.holding-today').first().innerText(),/\+.*\(\+1\.01%\)/s);
// All saved accounts must appear even when another account is preselected.
for(const name of ['퇴직연금','일반계좌']){await page.locator('#add-account').click();await page.locator('#account-name').fill(name);await page.locator('#account-form button[type="submit"]').click()}
await page.locator('#add-holding').click();await page.locator('.search-result').filter({hasText:'KODEX 200'}).click();assert.deepEqual(await page.locator('#account option').allTextContents(),['ISA','퇴직연금','일반계좌','+ 새 계좌']);await page.locator('#account').selectOption('퇴직연금');await page.locator('#quantity').fill('1');await page.locator('#cost').fill('40000');await page.locator('#holding-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).holdings.at(-1).account),'퇴직연금');
await page.locator('[data-edit]').last().click();assert.equal(await page.locator('#account').inputValue(),'퇴직연금');await page.locator('#account').selectOption('일반계좌');await page.locator('#holding-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).holdings.at(-1).account),'일반계좌');
for(const width of [320,390,760]){await page.setViewportSize({width,height:844});const boxes=await page.locator('nav button').evaluateAll(bs=>bs.map(b=>({icon:b.querySelector('svg').getBoundingClientRect().bottom,label:b.querySelector('.nav-label').getBoundingClientRect().top})));assert(boxes.every(b=>b.icon+4<=b.label),'Navigation icon and label overlap')}
await page.setViewportSize({width:390,height:844});
await page.locator('[data-portfolio-view="accounts"]').click();assert.equal(await page.locator('.account-group').count(),3);await page.locator('#collapse-accounts').click();assert.equal(await page.locator('.account-group[open]').count(),0);assert.match(await page.locator('.account-group summary').first().innerText(),/매입금액/);await page.clock.runFor(25000);assert.equal(await page.locator('.account-group[open]').count(),0);await page.locator('#expand-accounts').click();assert.equal(await page.locator('.account-group[open]').count(),3);await page.locator('[data-portfolio-view="all"]').click();assert.equal(await page.locator('.account-group').count(),0);assert.equal(await page.locator('[data-edit]').count(),3);
await page.locator('#add-holding').click();await page.locator('[data-market="US"]').click();await page.locator('.search-result').filter({hasText:'애플'}).click();await page.locator('#account').selectOption('퇴직연금');await page.locator('#quantity').fill('2');await page.locator('#cost').fill('130');await page.locator('#holding-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelectorAll('.holding-row').length===4);await page.locator('[data-portfolio-view="symbols"]').click();assert.equal(await page.locator('.holding-row').count(),3);const apple=page.locator('[data-holding-symbol="AAPL"]');assert.match(await apple.locator('.holding-quantity').innerText(),/4주/);assert.match(await apple.locator('.holding-price small').innerText(),/115.00/);assert.match(await apple.locator('.holding-profit').innerText(),/\+20.00.*\(\+4.3%\)/s);await apple.locator('[data-members]').click();assert.equal(await page.locator('[data-member-edit]').count(),2);await page.locator('[data-member-edit]').last().click();assert.equal(await page.locator('#account').inputValue(),'퇴직연금');await page.locator('#close-dialog').click();await page.locator('[data-portfolio-view="all"]').click();assert.equal(await page.locator('.holding-row').count(),4);assert.doesNotMatch(await page.locator('#main').innerText(),/최근 시세/);assert.equal(await page.locator('.holding-table-head').count(),1);
await page.locator('[data-portfolio-view="accounts"]').click();assert.match(await page.locator('[data-account-group="퇴직연금"] .account-total').innerText(),/260.00/);await page.locator('[data-portfolio-view="all"]').click();let quoteCalls=await page.evaluate(()=>__quoteCalls);await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);await page.locator('#refresh').click();await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);assert((await page.evaluate(()=>__quoteCalls))>quoteCalls);assert.match(await page.locator('#toast').innerText(),/새로 불러/);
// Long names must truncate within the identity cell without displacing the edit button.
await page.evaluate(()=>{state.holdings[1].name='KODEX 삼성전자SK하이닉스채권혼합50 긴 종목명';render()});await page.waitForSelector('.holding-row');for(const width of [320,390,760]){await page.setViewportSize({width,height:844});const layout=await page.locator('.holding-identity').evaluateAll(es=>es.map(e=>({cell:e.getBoundingClientRect().right,button:e.querySelector('.edit-holding').getBoundingClientRect().right,name:e.querySelector('.holding-title').getBoundingClientRect().bottom,edit:e.querySelector('.edit-holding').getBoundingClientRect().top})));assert(layout.every(x=>x.button<=x.cell+1&&x.name<=x.edit+1));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)}await page.setViewportSize({width:390,height:844});
fs.mkdirSync(path.resolve(__dirname,'../verification'),{recursive:true});await page.screenshot({path:path.resolve(__dirname,'../verification/portfolio-phone.png'),fullPage:true});
await page.locator('[data-tab="watch"]').click();quoteCalls=await page.evaluate(()=>__quoteCalls);await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);await page.locator('#refresh').click();await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);assert((await page.evaluate(()=>__quoteCalls))>quoteCalls);const cards=await page.locator('.watch-card').evaluateAll(xs=>xs.map(x=>x.getBoundingClientRect().top));assert(cards[1]>cards[0]);const head=await page.locator('.section-head').first().boundingBox(),index=await page.locator('.index-panel').boundingBox();assert(index.y>head.y+head.height);await page.locator('[data-alert="005930.KS"]').click();await page.locator('#target').fill('90000');await page.locator('#alert-form button[type="submit"]').click();assert.equal(await page.evaluate(()=>JSON.parse(__saved).rules[0].target),90000);
await page.locator('#add-watch').click();for(const code of ['000660','035420','035720','005380','360750','133690','041510','003550']){await page.locator('#query').fill(code);await page.locator('#search-form button').click();await page.locator('.search-result').filter({hasText:code+'.KS'}).click()}assert.match(await page.locator('#selection-count').innerText(),/8개 선택/);assert.equal(await page.evaluate(()=>JSON.parse(__saved).watch.length),2);await page.locator('#query').fill('009150');await page.locator('#search-form button').click();await page.locator('.search-result').filter({hasText:'009150.KS'}).click();assert.match(await page.locator('#selection-count').innerText(),/9개 선택/);assert.equal(await page.locator('.search-result.checked .check-box svg').count(),1);await page.locator('#confirm-watch').click();
assert.equal(await page.locator('.watch-card').count(),11);assert.equal(await page.evaluate(()=>JSON.parse(__saved).watch.length),11);await page.locator('#add-watch').click();assert.equal(await page.locator('dialog[open]').count(),1);await page.locator('#close-dialog').click();
// Delete through the detail dialog (no edit mode any more).
await page.locator('[data-detail="003550.KS"]').first().click();await page.locator('#remove-watch').click();await page.locator('#yes').click();assert.equal(await page.locator('.watch-card').count(),10);assert.equal(await page.locator('.index-quote').count(),2);await page.waitForFunction(()=>document.querySelectorAll('.watch-card .spark').length===10);
// Long-press drag reorders and persists; a short tap must not drag.
await page.evaluate(()=>window.scrollTo(0,0));
const order=()=>page.evaluate(()=>JSON.parse(__saved).watch.map(x=>x.symbol));const before=await order();
const box=async sym=>page.locator('[data-watch-symbol="'+sym+'"]').boundingBox();
let src=await box(before[0]),dst=await box(before[2]);
await page.mouse.move(src.x+src.width/2,src.y+src.height/2);await page.mouse.down();await page.mouse.move(src.x+src.width/2,src.y+src.height/2+4,{steps:2});await page.mouse.up();assert.deepEqual(await order(),before);assert.equal(await page.locator('dialog[open]').count(),1,'a short tap still opens the detail');await page.locator('#close-dialog').click();
await page.mouse.move(src.x+src.width/2,src.y+src.height/2);await page.mouse.down();await page.clock.runFor(400);assert.equal(await page.locator('.watch-card.dragging').count(),1);await page.mouse.move(dst.x+dst.width/2,dst.y+dst.height*0.8,{steps:10});await page.clock.runFor(50);await page.screenshot({path:path.resolve(__dirname,'../verification/watch-drag.png'),fullPage:true});await page.mouse.up();await page.clock.runFor(50);
const after=await order();assert.deepEqual(after,[before[1],before[2],before[0],...before.slice(3)]);assert.equal(await page.locator('.watch-card.dragging').count(),0);
// Dragging upward and a moving finger before the hold time (scroll) must not reorder.
src=await box(after[2]);dst=await box(after[0]);await page.mouse.move(src.x+src.width/2,src.y+src.height/2);await page.mouse.down();await page.clock.runFor(400);await page.mouse.move(dst.x+dst.width/2,dst.y+dst.height*0.2,{steps:10});await page.clock.runFor(50);await page.mouse.up();await page.clock.runFor(50);assert.deepEqual(await order(),[after[2],after[0],after[1],...after.slice(3)]);
src=await box(after[0]);await page.mouse.move(src.x+10,src.y+10);await page.mouse.down();await page.mouse.move(src.x+10,src.y+80,{steps:5});await page.clock.runFor(500);await page.mouse.up();assert.deepEqual(await order(),[after[2],after[0],after[1],...after.slice(3)]);
await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.resolve(__dirname,'../verification/watch-density.png'),fullPage:true});const visibleCards=await page.locator('.watch-card').evaluateAll(xs=>xs.filter(x=>x.getBoundingClientRect().bottom<innerHeight-76).length);assert(visibleCards>=5,'Compact rows should fit at least five full stocks');const geometry=await page.locator('.watch-card').first().evaluate(e=>({height:e.getBoundingClientRect().height,price:e.querySelector('.watch-price').getBoundingClientRect().right,chart:e.querySelector('.watch-chart').getBoundingClientRect().left}));assert(geometry.height<115);assert(geometry.chart>geometry.price);
// Refresh arrow rotates around its own centre.
const arrow=await page.locator('.refresh-icon').evaluate(e=>{const r=e.getBoundingClientRect(),b=e.closest('button').getBoundingClientRect();return {dx:Math.abs((r.left+r.width/2)-(b.left+b.width/2)),dy:Math.abs((r.top+r.height/2)-(b.top+b.height/2))}});assert(arrow.dx<1&&arrow.dy<1,'Refresh arrow must be centred in its button');
await page.locator('[data-tab="news"]').click();const newsCalls=await page.evaluate(()=>__newsCalls);await page.clock.fastForward(300000);await page.clock.runFor(100);assert((await page.evaluate(()=>__newsCalls))>newsCalls,'News must refresh after five minutes');assert.equal(await page.locator('.news-item').count(),10);await page.locator('[data-tab="watch"]').click();
await page.screenshot({path:path.resolve(__dirname,'../verification/watch-phone.png'),fullPage:true});await page.setViewportSize({width:760,height:1000});await page.screenshot({path:path.resolve(__dirname,'../verification/watch-fold.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.locator('[data-tab="settings"]').click();assert.equal(await page.locator('#export').count(),0);assert.equal(await page.locator('#import').count(),0);assert.doesNotMatch(await page.locator('#main').innerText(),/설정한 목표가/);assert.deepEqual(errors,[]);console.log('UI checks passed: chart, KR/US search selection, holdings, mixed account totals, target, backup, phone/fold widths.');
}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
